version = "1.0"

[main]
name = "Mediawiki configuration"

    [main.config]
    name = "Configuration Options"

        [main.config.create_account]
        ask = "Create account"
        type = "boolean"
        yes = true
        no = false
        help = "Set to 'true' to allow account creation."
        bind = "createaccount:__INSTALL_DIR__/LocalSettings.php"
