#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "mediawiki"
name = "MediaWiki"
description.en = "Wiki package originally for use on Wikipedia"
description.fr = "Wiki développé à l’origine pour Wikipédia"

version = "1.42.1~ynh1"

maintainers = ["Salamandar"]

[upstream]
license = "GPL-2.0-or-later"
website = "https://www.mediawiki.org"
demo = "https://www.wikipedia.org"
admindoc = "https://www.mediawiki.org/wiki/Documentation"
userdoc = "https://www.mediawiki.org/wiki/Project:Help"
code = "https://github.com/wikimedia/mediawiki"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = true
ldap = true
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/wiki"

    [install.init_main_permission]
    help.en = "Visibility of the wiki pages"
    help.fr = "La visibilité des pages du wiki"
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["en", "fr"]
    default = "en"

    [install.admin]
    type = "user"

    [install.password]
    help.en = "The password for the wiki administrator. It needs to be solid or the installation process will fail."
    help.fr = "Le mot de passe de l'administrateur du wiki. Il doit être solide, sinon l'installation échouera."
    type = "password"

    [install.wiki_name]
    ask.en = "Choose the application name"
    ask.fr = "Choisissez le nom de l'application"
    type = "string"
    default = "YunoWiki"

[resources]
    [resources.sources]
    [resources.sources.main]
    url = "https://releases.wikimedia.org/mediawiki/1.42/mediawiki-1.42.1.tar.gz"
    sha256 = "ec87af95a35dd09c34d52e02795652a030ab72955e431f08ca722a73737eba53"

    [resources.sources.ldap_groups]
    url = "https://github.com/wikimedia/mediawiki-extensions-LDAPGroups/archive/6daabcd3a5c4b3802597eef34437e1721393a611.tar.gz"
    sha256 = "0d41b44690c51cc91692a539406d4022e3f947cc4a5a8bbe9eaf01adab6f359b"
    in_subdir = true

    [resources.sources.ldap_authorization]
    url = "https://github.com/wikimedia/mediawiki-extensions-LDAPAuthorization/archive/d3ce8bd7758a70822ce29fdb169392b240d24ae5.tar.gz"
    sha256 = "5e1a163565e58df34931273d4319206ea6e2f55a7e0cf2ccccfbb52c3ec11212"
    in_subdir = true

    [resources.sources.pluggable_auth]
    url = "https://github.com/wikimedia/mediawiki-extensions-PluggableAuth/archive/db07c042430e5d85f1e4d005defa8478161c0856.tar.gz"
    sha256 = "02782b4ed938cf920ddbf94f84c552224a9bf9f03f7fe2e7a4b2a22e535980fa"
    in_subdir = true

    [resources.sources.ldap_authentication2]
    url = "https://github.com/wikimedia/mediawiki-extensions-LDAPAuthentication2/archive/8773d5a36aecd86afdeeb6b3d77320d1cf867be0.tar.gz"
    sha256 = "95f09f63c53f218bfd1e321e7edec2dd941a7f6bb63d37049f62f1c9576d2e2c"
    in_subdir = true

    [resources.sources.ldap_userinfo]
    url = "https://github.com/wikimedia/mediawiki-extensions-LDAPUserInfo/archive/eb5f4170a5458485b0736f27d84af36371bd0da6.tar.gz"
    sha256 = "99202474faf0251b6f3bc065bdea07fdf3fcb51f8da7e242ab6e09165d0fe303"
    in_subdir = true

    [resources.sources.ldap_provider]
    url = "https://github.com/wikimedia/mediawiki-extensions-LDAPProvider/archive/a73838c2868b22832ba2069d5a0db6f7b4abdfed.tar.gz"
    sha256 = "18afbc1619450c368144553a53b3f44d6867b3028570f9422ba950808eeb9426"
    in_subdir = true

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"
    api.url = "/api"
    api.allowed = "visitors"
    api.auth_header = false
    api.show_tile = false

    [resources.apt]
    packages = [
        "php8.3-fpm",
        "php8.3-mysql",
        "php8.3-mbstring",
        "php8.3-xml",
        "php8.3-intl",
        "mariadb-server",
        "diffutils",
        "imagemagick",
        "acl",
    ]

    [resources.database]
    type = "mysql"
