#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "mediawiki"
name = "MediaWiki"
description.en = "Wiki package originally for use on Wikipedia"
description.fr = "Wiki développé à l’origine pour Wikipédia"

version = "1.43.3~ynh2"

maintainers = ["Salamandar"]

[upstream]
license = "GPL-2.0-or-later"
website = "https://www.mediawiki.org"
demo = "https://www.wikipedia.org"
admindoc = "https://www.mediawiki.org/wiki/Documentation"
userdoc = "https://www.mediawiki.org/wiki/Project:Help"
code = "https://github.com/wikimedia/mediawiki"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = true
sso = false

disk = "750M"
ram.build = "150M"
ram.runtime = "150M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/wiki"

    [install.init_main_permission]
    help.en = "Visibility of the wiki pages"
    help.fr = "La visibilité des pages du wiki"
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["en", "fr"]
    default = "en"

    [install.admin]
    type = "user"

    [install.password]
    help.en = "The password for the wiki administrator. It needs to contain at least 10 characters or the installation will fail."
    help.fr = "Mot de passe de l'administrateur du wiki. Il doit comporter au moins 10 caractères, sinon l'installation échouera."
    type = "password"

    [install.wiki_name]
    ask.en = "Choose the application name"
    ask.fr = "Choisissez le nom de l'application"
    type = "string"
    default = "YunoWiki"

[resources]
    [resources.sources]
    [resources.sources.main]
    url = "https://releases.wikimedia.org/mediawiki/1.43/mediawiki-1.43.3.tar.gz"
    sha256 = "e409df416ba4d99d2705e1eb0ff8168863db2a791cc0be7a87db3c13d9801a70"

    [resources.sources.ldap_groups]
    url = "https://github.com/wikimedia/mediawiki-extensions-LDAPGroups/archive/66eecb305c8e2952f25b1facf63fef1e51e78109.tar.gz"
    sha256 = "d54fc0e3247b41fdcc5c02865d672ec6c3347cf57fb2f3a1eb09e050d9550b0d"
    in_subdir = true

    [resources.sources.ldap_authorization]
    url = "https://github.com/wikimedia/mediawiki-extensions-LDAPAuthorization/archive/95ae616f434a1ca8e46cdf9c72e58e17fcecaf13.tar.gz"
    sha256 = "d5d0f3bcdcbb13e8ac012c665e1ba0cdc324163ab07c75b97571d25b77a844b5"
    in_subdir = true

    [resources.sources.pluggable_auth]
    url = "https://github.com/wikimedia/mediawiki-extensions-PluggableAuth/archive/1a3250f50b4c24a6f989a65f08dad51739f1fc1e.tar.gz"
    sha256 = "55e6830e18a4c83c37fdf2b1ba96dd8c1339dc89fddd7445c1a8a8b3e14aa721"
    in_subdir = true

    [resources.sources.ldap_authentication2]
    url = "https://github.com/wikimedia/mediawiki-extensions-LDAPAuthentication2/archive/e906f4c574c59330594581ff7f488d78155ed0df.tar.gz"
    sha256 = "b4a10a2920ba3507310e6e07e67fb30e7bcbbbd8194fde13d8812e087974893b"
    in_subdir = true

    [resources.sources.ldap_userinfo]
    url = "https://github.com/wikimedia/mediawiki-extensions-LDAPUserInfo/archive/287727d4c96115e0e0a7da48cd15b8341f3e2578.tar.gz"
    sha256 = "c473c78d74d4e400973e531cea763676b75ad607e0ed020460b44f6bc22bdaa2"
    in_subdir = true

    [resources.sources.ldap_provider]
    url = "https://github.com/wikimedia/mediawiki-extensions-LDAPProvider/archive/74276a97dabfd683dd7262a822b9c7b2e2297f61.tar.gz"
    sha256 = "e91a0244489a93f6923e2e3a56280f018360b22f7c66365b7752d9d2494e4f7a"
    in_subdir = true

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"
    api.url = "/api"
    api.allowed = "visitors"
    api.auth_header = false
    api.show_tile = false

    [resources.apt]
    packages = [
        "php8.3-fpm",
        "php8.3-mysql",
        "php8.3-mbstring",
        "php8.3-xml",
        "php8.3-intl",
        "mariadb-server",
        "diffutils",
        "imagemagick",
        "acl",
    ]

    [resources.database]
    type = "mysql"
