#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "mediawiki"
name = "MediaWiki"
description.en = "Wiki package originally for use on Wikipedia"
description.fr = "Wiki développé à l’origine pour Wikipédia"

version = "1.40.1~ynh1"

maintainers = ["Salamandar"]

[upstream]
license = "GPL-2.0-or-later"
website = "https://www.mediawiki.org"
demo = "https://www.wikipedia.org"
admindoc = "https://www.mediawiki.org/wiki/Documentation"
userdoc = "https://www.mediawiki.org/wiki/Project:Help"
code = "https://github.com/wikimedia/mediawiki"

[integration]
yunohost = ">= 11.1.17"
architectures = "all"
multi_instance = true
ldap = true
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/wiki"

    [install.init_main_permission]
    help.en = "Visibility of the wiki pages"
    help.fr = "La visibilité des pages du wiki"
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["en", "fr"]
    default = "en"

    [install.admin]
    type = "user"

    [install.password]
    help.en = "The password for the wiki administrator. It needs to be solid or the installation process will fail."
    help.fr = "Le mot de passe de l'administrateur du wiki. Il doit être solide, sinon l'installation échouera."
    type = "password"

    [install.wiki_name]
    ask.en = "Choose the application name"
    ask.fr = "Choisissez le nom de l'application"
    type = "string"
    default = "YunoWiki"

[resources]
    [resources.sources]
    [resources.sources.main]
    url = "https://releases.wikimedia.org/mediawiki/1.40/mediawiki-1.40.1.tar.gz"
    sha256 = "e05d419de40c6ad03145aca07e08cf995d1ca1667d97793bb73970e2c11b0a04"

    [resources.sources.ldap_groups]
    url = "https://github.com/wikimedia/mediawiki-extensions-LDAPGroups/archive/e4c9b9c5d443a90c6ea8b2daae68e367d9266451.tar.gz"
    sha256 = "472ee2984674fcdc15acf09f45627d69d7f77186a29ae8a12e3555c9139fa24f"
    in_subdir = true

    [resources.sources.ldap_authorization]
    url = "https://github.com/wikimedia/mediawiki-extensions-LDAPAuthorization/archive/dc7fe20c0aab224a4d188187db9bc8492e946f29.tar.gz"
    sha256 = "e99a08e02502cad4dd21b55dfe3697bd41df4564a2a7e3de129ef7ab2128592e"
    in_subdir = true

    [resources.sources.pluggable_auth]
    url = "https://github.com/wikimedia/mediawiki-extensions-PluggableAuth/archive/dc6186d4c573f30f5edc1f8846951f879ac62e96.tar.gz"
    sha256 = "d2e28b703e455d794a59a1076ca79872c4527c3f664a313c9411eb0a6c60d2b0"
    in_subdir = true

    [resources.sources.ldap_authentication2]
    url = "https://github.com/wikimedia/mediawiki-extensions-LDAPAuthentication2/archive/f303c5544c1fd4bc4332ffbd3395765f9e67316b.tar.gz"
    sha256 = "fa1f62540d22606105914033dd21ced4fbf2bb56c28f84ea1f02c0e244890a4d"
    in_subdir = true

    [resources.sources.ldap_userinfo]
    url = "https://github.com/wikimedia/mediawiki-extensions-LDAPUserInfo/archive/40e886feb9f2e49dbd37888b541919395b1cb059.tar.gz"
    sha256 = "ced9cd10fac674999c70a23bfab43a08e8ebcd112de9a040da6af5c11f86de8f"
    in_subdir = true

    [resources.sources.ldap_provider]
    url = "https://github.com/wikimedia/mediawiki-extensions-LDAPProvider/archive/740f097174b58e9dd28d925a4f429b897183f13e.tar.gz"
    sha256 = "d49c80e8a5d97c7d91d07b11179668e46ab0c2b31e99680bd424308313e9c327"
    in_subdir = true

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = [
        "php8.1-fpm",
        "php8.1-mysql",
        "php8.1-mbstring",
        "php8.1-xml",
        "php8.1-intl",
        "mariadb-server",
        "diffutils",
        "imagemagick",
        "acl",
    ]

    [resources.database]
    type = "mysql"
