#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "mediawiki"
name = "MediaWiki"
description.en = "Wiki package originally for use on Wikipedia"
description.fr = "Wiki développé à l’origine pour Wikipédia"

version = "1.43.3~ynh2"

maintainers = ["Salamandar"]

[upstream]
license = "GPL-2.0-or-later"
website = "https://www.mediawiki.org"
demo = "https://www.wikipedia.org"
admindoc = "https://www.mediawiki.org/wiki/Documentation"
userdoc = "https://www.mediawiki.org/wiki/Project:Help"
code = "https://github.com/wikimedia/mediawiki"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = true
sso = false

disk = "750M"
ram.build = "150M"
ram.runtime = "150M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/wiki"

    [install.init_main_permission]
    help.en = "Visibility of the wiki pages"
    help.fr = "La visibilité des pages du wiki"
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["en", "fr"]
    default = "en"

    [install.admin]
    type = "user"

    [install.password]
    help.en = "The password for the wiki administrator. It needs to contain at least 10 characters or the installation will fail."
    help.fr = "Mot de passe de l'administrateur du wiki. Il doit comporter au moins 10 caractères, sinon l'installation échouera."
    type = "password"

    [install.wiki_name]
    ask.en = "Choose the application name"
    ask.fr = "Choisissez le nom de l'application"
    type = "string"
    default = "YunoWiki"

[resources]
    [resources.sources]
    [resources.sources.main]
    url = "https://releases.wikimedia.org/mediawiki/1.43/mediawiki-1.43.3.tar.gz"
    sha256 = "e409df416ba4d99d2705e1eb0ff8168863db2a791cc0be7a87db3c13d9801a70"

    [resources.sources.ldap_groups]
    url = "https://github.com/wikimedia/mediawiki-extensions-LDAPGroups/archive/e63107986091e79c196275bb73649504d4b1cff3.tar.gz"
    sha256 = "33952c760208da285a388b71e8599612e4a01c82feb8b11437bcb4f9fb1a4f46"
    in_subdir = true

    [resources.sources.ldap_authorization]
    url = "https://github.com/wikimedia/mediawiki-extensions-LDAPAuthorization/archive/d043a12717964c78e26fe92a7eeae90d6fe30ad0.tar.gz"
    sha256 = "3de2009084c37d6ef827d9a4a0d7c21f9de3d769cdb9eb6bd4818edfd7d4813b"
    in_subdir = true

    [resources.sources.pluggable_auth]
    url = "https://github.com/wikimedia/mediawiki-extensions-PluggableAuth/archive/f7ba03299b82780ebc792c79780f46b4dc0cec37.tar.gz"
    sha256 = "76e5ea7e1ba3628a538bcb71fb154d5017db831d7a0e8064fdf876711eb8cfb5"
    in_subdir = true

    [resources.sources.ldap_authentication2]
    url = "https://github.com/wikimedia/mediawiki-extensions-LDAPAuthentication2/archive/fbf7b375bcd7c502dffce33b4d31a539532e2312.tar.gz"
    sha256 = "7ffaa3065d93a41ac20e385dca8496501019ee2a6b957de9f210d3fe61073ac8"
    in_subdir = true

    [resources.sources.ldap_userinfo]
    url = "https://github.com/wikimedia/mediawiki-extensions-LDAPUserInfo/archive/0cc076bf077e96727b2a7417ebb02a24a1f03f15.tar.gz"
    sha256 = "b9bba82bdd49f40c1668a3bae0f74fad0684d40b69bb8d67a79466a7f5b0864a"
    in_subdir = true

    [resources.sources.ldap_provider]
    url = "https://github.com/wikimedia/mediawiki-extensions-LDAPProvider/archive/712ad9ba18ca065e0997de593cfd765a6f67ab57.tar.gz"
    sha256 = "9dec8e84259d1e3212a78fb662d10782fea8efff5548f4824402d2050785be1b"
    in_subdir = true

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"
    api.url = "/api"
    api.allowed = "visitors"
    api.auth_header = false
    api.show_tile = false

    [resources.apt]
    packages = [
        "php8.3-fpm",
        "php8.3-mysql",
        "php8.3-mbstring",
        "php8.3-xml",
        "php8.3-intl",
        "mariadb-server",
        "diffutils",
        "imagemagick",
        "acl",
    ]

    [resources.database]
    type = "mysql"
