#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "mediawiki"
name = "MediaWiki"
description.en = "Wiki package originally for use on Wikipedia"
description.fr = "Wiki développé à l’origine pour Wikipédia"

version = "1.42.1~ynh1"

maintainers = ["Salamandar"]

[upstream]
license = "GPL-2.0-or-later"
website = "https://www.mediawiki.org"
demo = "https://www.wikipedia.org"
admindoc = "https://www.mediawiki.org/wiki/Documentation"
userdoc = "https://www.mediawiki.org/wiki/Project:Help"
code = "https://github.com/wikimedia/mediawiki"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = true
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/wiki"

    [install.init_main_permission]
    help.en = "Visibility of the wiki pages"
    help.fr = "La visibilité des pages du wiki"
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["en", "fr"]
    default = "en"

    [install.admin]
    type = "user"

    [install.password]
    help.en = "The password for the wiki administrator. It needs to be solid or the installation process will fail."
    help.fr = "Le mot de passe de l'administrateur du wiki. Il doit être solide, sinon l'installation échouera."
    type = "password"

    [install.wiki_name]
    ask.en = "Choose the application name"
    ask.fr = "Choisissez le nom de l'application"
    type = "string"
    default = "YunoWiki"

[resources]
    [resources.sources]
    [resources.sources.main]
    url = "https://releases.wikimedia.org/mediawiki/1.42/mediawiki-1.42.1.tar.gz"
    sha256 = "ec87af95a35dd09c34d52e02795652a030ab72955e431f08ca722a73737eba53"

    [resources.sources.ldap_groups]
    url = "https://github.com/wikimedia/mediawiki-extensions-LDAPGroups/archive/b416866398d9d69edea13cedf18e0065938e3f48.tar.gz"
    sha256 = "c9fb123a422d248b944e926fc18247ec264f45325c160563df534deba44594a4"
    in_subdir = true

    [resources.sources.ldap_authorization]
    url = "https://github.com/wikimedia/mediawiki-extensions-LDAPAuthorization/archive/d1f680b286466b072ec275c516e63d49e906009e.tar.gz"
    sha256 = "27dd4860305666499d0ac66b97355e749cf949636b8da22954fafa8761b51c3e"
    in_subdir = true

    [resources.sources.pluggable_auth]
    url = "https://github.com/wikimedia/mediawiki-extensions-PluggableAuth/archive/de411792c3005417b27279ce903357cab2e60422.tar.gz"
    sha256 = "97fcf0549e0c60e9ea98e6b9642deaa55124597f040175d9b92e987f7e292024"
    in_subdir = true

    [resources.sources.ldap_authentication2]
    url = "https://github.com/wikimedia/mediawiki-extensions-LDAPAuthentication2/archive/7bb88f979cc85ae01ef128bc5ee806fe4d44594c.tar.gz"
    sha256 = "e7a58292b03784325485c273ec7775d223dd62225f338cd01bc6b45722cd666b"
    in_subdir = true

    [resources.sources.ldap_userinfo]
    url = "https://github.com/wikimedia/mediawiki-extensions-LDAPUserInfo/archive/9d751aab40857fad1176e081c6ff3061ddb49ce5.tar.gz"
    sha256 = "d63d202524839daddd6dd79f6fb0a22a77618b45cb339812d023b6240f192c6a"
    in_subdir = true

    [resources.sources.ldap_provider]
    url = "https://github.com/wikimedia/mediawiki-extensions-LDAPProvider/archive/8765eeacbf80927f8f48a03e6f92dfe47f6901c2.tar.gz"
    sha256 = "f35ea93d09135c8657efebc2502d7e0bd43ec09bbeee89ee372c9bdc8abe55db"
    in_subdir = true

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    api.url = "/api"
    api.allowed = "visitors"
    api.auth_header = false
    api.show_tile = false

    [resources.apt]
    packages = [
        "php8.1-fpm",
        "php8.1-mysql",
        "php8.1-mbstring",
        "php8.1-xml",
        "php8.1-intl",
        "mariadb-server",
        "diffutils",
        "imagemagick",
        "acl",
    ]

    [resources.database]
    type = "mysql"
