#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "mediawiki"
name = "MediaWiki"
description.en = "Wiki package originally for use on Wikipedia"
description.fr = "Wiki développé à l’origine pour Wikipédia"

version = "1.43.1~ynh1"

maintainers = ["Salamandar"]

[upstream]
license = "GPL-2.0-or-later"
website = "https://www.mediawiki.org"
demo = "https://www.wikipedia.org"
admindoc = "https://www.mediawiki.org/wiki/Documentation"
userdoc = "https://www.mediawiki.org/wiki/Project:Help"
code = "https://github.com/wikimedia/mediawiki"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = true
ldap = true
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/wiki"

    [install.init_main_permission]
    help.en = "Visibility of the wiki pages"
    help.fr = "La visibilité des pages du wiki"
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["en", "fr"]
    default = "en"

    [install.admin]
    type = "user"

    [install.password]
    help.en = "The password for the wiki administrator. It needs to be solid or the installation process will fail."
    help.fr = "Le mot de passe de l'administrateur du wiki. Il doit être solide, sinon l'installation échouera."
    type = "password"

    [install.wiki_name]
    ask.en = "Choose the application name"
    ask.fr = "Choisissez le nom de l'application"
    type = "string"
    default = "YunoWiki"

[resources]
    [resources.sources]
    [resources.sources.main]
    url = "https://releases.wikimedia.org/mediawiki/1.43/mediawiki-1.43.1.tar.gz"
    sha256 = "3c85aa9c4cd6c353c67804a3a58e7b79615d4141c3d66b101e5f3aeb40653d6c"

    [resources.sources.ldap_groups]
    url = "https://github.com/wikimedia/mediawiki-extensions-LDAPGroups/archive/de82185ac432334543a47592b80872f5137c229a.tar.gz"
    sha256 = "d9071001adf5f0c463b0bddffa7a704c91b6196dbd5f10e4d29de5b82f378745"
    in_subdir = true

    [resources.sources.ldap_authorization]
    url = "https://github.com/wikimedia/mediawiki-extensions-LDAPAuthorization/archive/582abeb950dccd9ecbf5fd61749b6389086476bf.tar.gz"
    sha256 = "3214ccc6af14c6e0c09f84bccd0c91aa09d53a1615f3e24b391546eeffe18dd1"
    in_subdir = true

    [resources.sources.pluggable_auth]
    url = "https://github.com/wikimedia/mediawiki-extensions-PluggableAuth/archive/0623100153e96bc8e345cbc8f8dfd4075523bd4d.tar.gz"
    sha256 = "5802362435a40ed8122e2ba4744cbd330deadf01f9663ff2b93934e64b870228"
    in_subdir = true

    [resources.sources.ldap_authentication2]
    url = "https://github.com/wikimedia/mediawiki-extensions-LDAPAuthentication2/archive/d081b79ccdc95e885818e4a6c0c0287253f76b71.tar.gz"
    sha256 = "3cbcd9b5c82c555debe3c8104b9f3a8fa86a488f0905b9c8e7ff64515cc181fc"
    in_subdir = true

    [resources.sources.ldap_userinfo]
    url = "https://github.com/wikimedia/mediawiki-extensions-LDAPUserInfo/archive/12473e0388f769699359c78ff813d4a6e70d7ae8.tar.gz"
    sha256 = "37e99f916da45545b902e3b2af7bd4633b919b0f39c1aa7e8a264c862180de03"
    in_subdir = true

    [resources.sources.ldap_provider]
    url = "https://github.com/wikimedia/mediawiki-extensions-LDAPProvider/archive/684a64689408ae02bff40dfe47ffdf69bc221443.tar.gz"
    sha256 = "ed0c8c894b72ebd24def07f336a273784095a18549984e737ef0826eca2d2851"
    in_subdir = true

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"
    api.url = "/api"
    api.allowed = "visitors"
    api.auth_header = false
    api.show_tile = false

    [resources.apt]
    packages = [
        "php8.3-fpm",
        "php8.3-mysql",
        "php8.3-mbstring",
        "php8.3-xml",
        "php8.3-intl",
        "mariadb-server",
        "diffutils",
        "imagemagick",
        "acl",
    ]

    [resources.database]
    type = "mysql"
