packaging_format = 2

id = "mediawiki"
name = "MediaWiki"
description.en = "Wiki package originally for use on Wikipedia"
description.fr = "Wiki développé à l’origine pour Wikipédia"

version = "1.40.0~ynh1"

maintainers = ["Salamandar"]

[upstream]
license = "GPL-2.0-or-later"
website = "https://www.mediawiki.org"
demo = "https://www.wikipedia.org"
admindoc = "https://www.mediawiki.org/wiki/Documentation"
userdoc = "https://www.mediawiki.org/wiki/Project:Help"
code = "https://github.com/wikimedia/mediawiki"

[integration]
yunohost = ">= 11.1.17"
architectures = "all"
multi_instance = true
ldap = true
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/wiki"

    [install.init_main_permission]
    help.en = "Visibility of the wiki pages"
    help.fr = "La visibilité des pages du wiki"
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["en", "fr"]
    default = "en"

    [install.admin]
    type = "user"

    [install.password]
    help.en = "The password for the wiki administrator. It needs to be solid or the installation process will fail."
    help.fr = "Le mot de passe de l'administrateur du wiki. Il doit être solide, sinon l'installation échouera."
    type = "password"

    [install.wiki_name]
    ask.en = "Choose the application name"
    ask.fr = "Choisissez le nom de l'application"
    type = "string"
    default = "YunoWiki"

[resources]
    [resources.sources]
        [resources.sources.main]
        url = "https://releases.wikimedia.org/mediawiki/1.40/mediawiki-1.40.0.tar.gz"
        sha256 = "e9c4877718698f082d8096d8a9d16cd9aeb21ee1982a3d8b4603af7cfd158ad4"

        [resources.sources.ldap_groups]
        url = "https://github.com/wikimedia/mediawiki-extensions-LDAPGroups/archive/16c55290eb60e21e169b0eedb91167fb075f9663.tar.gz"
        sha256 = "858c020358b354a550f71c65517f07cf6a199b428acb21c7c7745e34e24ff465"
        in_subdir = true

        [resources.sources.ldap_authorization]
        url = "https://github.com/wikimedia/mediawiki-extensions-LDAPAuthorization/archive/2408534d03c4c57e3f01233fc7ec5e04fae3f783.tar.gz"
        sha256 = "75678f6200d75dda0c42a98621222aa7b10a5ff909e480decb6e9efeb1172a0e"
        in_subdir = true

        [resources.sources.pluggable_auth]
        url = "https://github.com/wikimedia/mediawiki-extensions-PluggableAuth/archive/8104ed91f386ddbd03ece9a390f9b23f4f6eb4b3.tar.gz"
        sha256 = "8f9648cd862ad4f24d28a595d51b82f398b7bddaec9a0a5f82058a5d4a34e08a"
        in_subdir = true

        [resources.sources.ldap_authentication2]
        url = "https://github.com/wikimedia/mediawiki-extensions-LDAPAuthentication2/archive/2864ae95874653c2e89f66d1423f41fc3d00705e.tar.gz"
        sha256 = "c6940ab2e3daf09b1b89c704a9c9dcc86c45a3efbc7006214b578e2d95aa0be0"
        in_subdir = true

        [resources.sources.ldap_userinfo]
        url = "https://github.com/wikimedia/mediawiki-extensions-LDAPUserInfo/archive/3ccc578e50ccb197f7f19400fbb6cf88f50181cf.tar.gz"
        sha256 = "166aab9e826eed000de749e4b2fd31321eb160c08674ea558b7e7e1862778fb3"
        in_subdir = true

        [resources.sources.ldap_provider]
        url = "https://github.com/wikimedia/mediawiki-extensions-LDAPProvider/archive/99edc230e687d67aaa50dff00435fd99fddc0568.tar.gz"
        sha256 = "837f302add103e1498dca4ded17e491e584ad3d7e4cca3a7e86dc07e52cd8e76"
        in_subdir = true

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "php8.0-fpm php8.0-mysql php8.0-mbstring php8.0-xml php8.0-intl mariadb-server diffutils imagemagick acl"

    [resources.database]
    type = "mysql"
