#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.password="1Strong-Password"
    args.wiki_name="MyYunoWiki"

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------
