#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================
source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS
#=================================================
old_domain=$YNH_APP_OLD_DOMAIN
old_path=$YNH_APP_OLD_PATH
new_domain=$YNH_APP_NEW_DOMAIN
new_path=$YNH_APP_NEW_PATH
app=$YNH_APP_INSTANCE_NAME

#=================================================
# LOAD SETTINGS
#=================================================
ynh_script_progression --message="Loading installation settings..." --weight=1

final_path=$(ynh_app_setting_get $app final_path)

#=================================================
# CHECK THE SYNTAX OF THE PATHS
#=================================================
test -n "$old_path" || old_path="/"
test -n "$new_path" || new_path="/"

new_path=$(ynh_normalize_url_path $new_path)
old_path=$(ynh_normalize_url_path $old_path)

#=================================================
# CHECK WHICH PARTS SHOULD BE CHANGED
#=================================================
change_domain=0
if [ "$old_domain" != "$new_domain" ]
then
  change_domain=1
fi

change_path=0
if [ "$old_path" != "$new_path" ]
then
  change_path=1
fi

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression --message="Updating nginx web server configuration..." --weight=1

nginx_conf_path=/etc/nginx/conf.d/$old_domain.d/$app.conf

if [ $change_path -eq 1 ]
then
  ynh_backup_if_checksum_is_different --file="$nginx_conf_path"
  domain="$old_domain"
  path_url="$new_path"
  ynh_add_nginx_config
fi

if [ $change_domain -eq 1 ]
then
  ynh_delete_file_checksum --file="$nginx_conf_path"
  mv $nginx_conf_path /etc/nginx/conf.d/$new_domain.d/$app.conf
  ynh_store_file_checksum --file="/etc/nginx/conf.d/$new_domain.d/$app.conf"
fi

#=================================================
# SET NEW URL
#=================================================
if [ $change_domain -eq 1 ]
then
  ynh_replace_string  --match_string="\$wgServer = \"https://$old_domain\";" --replace_string="\$wgServer = \"https://$new_domain\";" --target_file="$final_path/LocalSettings.php"
fi

if [ $change_path -eq 1 ]
then
  if [ "$old_path" = "/" ]; then
    old_scriptpath=""
  else
    old_scriptpath=$old_path
  fi

  if [ "$new_path" = "/" ]; then
    new_scriptpath=""
  else
    new_scriptpath=$new_path
  fi

  ynh_replace_string --match_string="\$wgScriptPath = \"$old_scriptpath\";" --replace_string="\$wgScriptPath = \"$new_scriptpath\";" --target_file="$final_path/LocalSettings.php"
fi 

#=================================================
# RELOAD NGINX
#=================================================
ynh_script_progression --message="Reloading nginx web server..." --weight=1

ynh_systemd_action --service_name=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression --message="Change of URL completed for $app" --last
