#!/bin/bash

db_user=mediawiki
db_name=mediawiki
root_pwd=$(sudo cat /etc/yunohost/mysql)
domain=$(sudo yunohost app setting mediawiki domain)

mysql -u root -p$root_pwd -e "DROP DATABASE $db_name ; DROP USER $db_user@localhost ;"
sudo rm -rf /var/www/mediawiki
sudo rm -f /etc/nginx/conf.d/$domain.d/mediawiki.conf